export const DEMO_CONTRACT_ID = "demo-contract-001";
export const DEMO_JOB_ID = "demo-job-001";

export const DEMO_CLAUSES = [
  {
    id: "clause-001",
    contract_id: DEMO_CONTRACT_ID,
    text: "The Employee agrees that during the term of employment and for a period of two (2) years following termination, the Employee shall not engage in any business that competes directly or indirectly with the Employer within a radius of fifty (50) miles of any of the Employer's offices.",
    position_index: 0,
    risk_level: "HIGH" as const,
    risk_category: "non_compete" as const,
    plain_english: "You cannot work for a competitor for 2 years within 50 miles after leaving your job.",
    worst_case: "You may be unable to find employment in your field for up to 2 years, forcing you to relocate or leave your profession entirely.",
    financial_exposure: "$250,000",
    negotiable: true,
    confidence: 0.65,
    headline: "Broad Non-Compete Clause Restricts Your Career",
    scenario: "This clause prohibits you from working for any competing business within 50 miles for 2 years after leaving. Courts frequently enforce such clauses, meaning you could be sued if you take a job with a competitor. This effectively traps you in your current role or forces you to leave the area.",
    probability: "High" as const,
    similar_case: "Silguero v. Creteguard, Inc. (2010)",
  },
  {
    id: "clause-002",
    contract_id: DEMO_CONTRACT_ID,
    text: "All intellectual property, including but not limited to inventions, discoveries, improvements, designs, works of authorship, and trade secrets, conceived, developed, or reduced to practice by the Employee during the term of employment, whether during working hours or using company resources or not, shall be the sole and exclusive property of the Company.",
    position_index: 1,
    risk_level: "HIGH" as const,
    risk_category: "ip_assignment" as const,
    plain_english: "Any invention, code, writing, or idea you create while employed belongs entirely to the company — even if done on your own time with your own equipment.",
    worst_case: "You lose all rights to any apps, products, or inventions you create — even ones created entirely on your own time that have nothing to do with the company's business.",
    financial_exposure: "$2,000,000",
    negotiable: true,
    confidence: 0.88,
    headline: "Full IP Assignment Captures All Your Future Work",
    scenario: "This clause claims ownership over ALL intellectual property you create during your employment, regardless of whether it's related to the company's business or created on your own time. California law limits such broad clauses, but if you're in another state, this could strip you of rights to personal projects, side businesses, or even code you write on weekends.",
    probability: "Medium" as const,
    similar_case: "Access Media v. ESPN (2013)",
  },
  {
    id: "clause-003",
    contract_id: DEMO_CONTRACT_ID,
    text: "The Company may terminate this Agreement at any time, with or without cause, without prior notice, and without any severance obligation. The Employee hereby waives any right to advance notice, severance pay, or any other compensation upon termination.",
    position_index: 2,
    risk_level: "HIGH" as const,
    risk_category: "termination" as const,
    plain_english: "The company can fire you immediately, for any reason or no reason, and you waive any right to notice or severance pay.",
    worst_case: "You could be terminated today with no warning, no severance, and no explanation — leaving you suddenly without income.",
    financial_exposure: "$75,000",
    negotiable: false,
    confidence: 0.95,
    headline: "Termination at Will with No Severance Protection",
    scenario: "This clause allows the company to fire you immediately without any notice or severance. While employment at-will is standard, explicitly waiving severance rights means you have zero financial cushion if terminated. Without cause protections, you have no legal recourse even if fired unfairly.",
    probability: "High" as const,
    similar_case: "Kerr v. Baranow (2009)",
  },
  {
    id: "clause-004",
    contract_id: DEMO_CONTRACT_ID,
    text: "The Employee agrees to assign to the Company all rights, title, and interest in any patents, copyrights, trademarks, or other intellectual property rights arising from work performed using company time, equipment, facilities, or resources, including but not limited to pre-existing IP that is incorporated into company products.",
    position_index: 3,
    risk_level: "MEDIUM" as const,
    risk_category: "ip_assignment" as const,
    plain_english: "Any IP created using company resources belongs to the company, and they can even claim pre-existing work you incorporated.",
    worst_case: "Your prior work, open source contributions, or personal projects may be claimed as company property if you ever use them in your work.",
    financial_exposure: "Unknown",
    negotiable: true,
    confidence: 0.82,
    headline: "Company Resources Clause May Claim Personal Projects",
    scenario: "This clause extends IP ownership to work created using company resources. If you occasionally check personal email on your work laptop or use company WiFi for a side project, those projects could be claimed as company IP. The 'pre-existing IP' provision is particularly aggressive and may be unenforceable in many jurisdictions.",
    probability: "Medium" as const,
    similar_case: "Sega v. Belega (2009)",
  },
  {
    id: "clause-005",
    contract_id: DEMO_CONTRACT_ID,
    text: "The Employee shall indemnify and hold harmless the Company from any claims, damages, losses, or expenses (including reasonable attorney fees) arising from the Employee's breach of this Agreement, negligence, or willful misconduct, whether by action or omission.",
    position_index: 4,
    risk_level: "MEDIUM" as const,
    risk_category: "indemnity" as const,
    plain_english: "You agree to pay the company's legal costs if they get sued because of something you did or failed to do.",
    worst_case: "If a client sues the company claiming your work caused harm, you could be personally liable for the company's legal defense costs.",
    financial_exposure: "$500,000",
    negotiable: true,
    confidence: 0.78,
    headline: "Indemnification Clause Creates Personal Liability",
    scenario: "This broad indemnification clause could make you personally responsible for legal costs if your actions (or omissions) lead to lawsuits against the company. In consulting or contractor relationships, this is particularly dangerous — it means you're on the hook for the company's legal defense even for matters beyond your control.",
    probability: "Medium" as const,
    similar_case: "Nakahara v. NS Design (2001)",
  },
  {
    id: "clause-006",
    contract_id: DEMO_CONTRACT_ID,
    text: "This agreement shall automatically renew for successive one (1) year periods unless either party provides written notice of non-renewal at least sixty (60) days prior to the end of the then-current term.",
    position_index: 5,
    risk_level: "MEDIUM" as const,
    risk_category: "auto_renewal" as const,
    plain_english: "This contract automatically renews every year forever unless you give 60 days notice. Miss the deadline and you're locked in for another year.",
    worst_case: "You could be stuck in a contract you want to exit simply by forgetting to send a notice 60 days in advance.",
    financial_exposure: "$120,000",
    negotiable: true,
    confidence: 0.91,
    headline: "Auto-Renewal Trap Locks You Indefinitely",
    scenario: "This automatic renewal clause means the contract extends for another year unless you actively cancel 60 days before expiry. This is a common trap — employees often forget the deadline and find themselves locked in for another 12 months. Some states require clear disclosure of renewal terms, but not all do.",
    probability: "Medium" as const,
    similar_case: "FTC v. Wyndham (2014)",
  },
  {
    id: "clause-007",
    contract_id: DEMO_CONTRACT_ID,
    text: "The Employee acknowledges and agrees that the total liability of the Company under this Agreement, whether in contract, tort, or otherwise, shall not exceed the total fees paid by the Company to the Employee in the twelve (12) months preceding the claim.",
    position_index: 6,
    risk_level: "LOW" as const,
    risk_category: "limitation_of_liability" as const,
    plain_english: "The company's legal liability to you is capped at what they paid you in the last year.",
    worst_case: "If the company causes you significant financial harm, your maximum recovery is limited to a year of your salary.",
    financial_exposure: "Capped at $80,000",
    negotiable: true,
    confidence: 0.85,
    headline: "Liability Cap Protects Company at Your Expense",
    scenario: "This clause limits the company's liability to you to just 12 months of fees. If the company breaches the contract in ways that cause you $500,000 in damages, you can only recover $80,000 at most. While companies often include these caps to protect themselves, they rarely offer reciprocal protection for employees.",
    probability: "Low" as const,
    similar_case: null,
  },
  {
    id: "clause-008",
    contract_id: DEMO_CONTRACT_ID,
    text: "Payment terms: Net 30 days from invoice date. Late payments shall accrue interest at a rate of 1.5% per month (18% APR) on the outstanding balance.",
    position_index: 7,
    risk_level: "LOW" as const,
    risk_category: "payment" as const,
    plain_english: "You get paid within 30 days of invoicing. If you're late, you pay 1.5% monthly interest.",
    worst_case: "Standard payment terms — the interest clause is typical for business contracts.",
    financial_exposure: null,
    negotiable: true,
    confidence: 0.95,
    headline: "Standard Net 30 Payment Terms",
    scenario: "This is a standard Net 30 payment term, which is common and reasonable in business relationships. The interest clause for late payments (1.5% per month) is also typical. Both parties are subject to the same terms, making this a balanced provision.",
    probability: "Low" as const,
    similar_case: null,
  },
  {
    id: "clause-009",
    contract_id: DEMO_CONTRACT_ID,
    text: "This Agreement shall be governed by and construed in accordance with the laws of the State of Delaware, without regard to its conflict of laws principles.",
    position_index: 8,
    risk_level: "SAFE" as const,
    risk_category: "governing_law" as const,
    plain_english: "Delaware law applies to this contract, and Delaware courts have jurisdiction over any disputes.",
    worst_case: "Standard legal provision — Delaware is actually known for having fair and efficient business courts.",
    financial_exposure: null,
    negotiable: true,
    confidence: 0.99,
    headline: "Delaware Governing Law — Favorable Business Jurisdiction",
    scenario: "Delaware is the most popular state for commercial contracts because it has sophisticated business law, an efficient court system (Court of Chancery), and experienced judges rather than juries for contract disputes. While some view out-of-state jurisdiction as a burden, Delaware is actually considered a pro-business, neutral venue.",
    probability: null,
    similar_case: null,
  },
  {
    id: "clause-010",
    contract_id: DEMO_CONTRACT_ID,
    text: "Any notice required or permitted under this Agreement shall be in writing and delivered by email to the addresses provided by each party. Email shall constitute valid delivery for all purposes under this Agreement.",
    position_index: 9,
    risk_level: "SAFE" as const,
    risk_category: "other" as const,
    plain_english: "All official communications between parties can be done via email.",
    worst_case: "Standard communication provision — no risk identified.",
    financial_exposure: null,
    negotiable: true,
    confidence: 0.98,
    headline: "Email Notice Provision — Standard & Efficient",
    scenario: "This is a straightforward provision allowing electronic communication, which is standard in modern contracts. Email delivery is widely accepted as valid legal notice in most jurisdictions. This clause creates no risk and simply makes administrative processes more efficient for both parties.",
    probability: null,
    similar_case: null,
  },
];

export const DEMO_SUMMARY = {
  one_liner: "This contract contains significant risks including an overly broad non-compete clause, complete IP assignment of your personal work, and at-will termination without severance. Recommend negotiating key changes before signing.",
  should_you_sign: "yes_with_changes" as const,
  top_3_concerns: [
    "Non-compete clause restricts employment for 2 years within 50 miles",
    "Full IP assignment could claim ownership of your personal projects",
    "Termination at will with no severance or notice requirements",
  ],
  top_2_positives: [
    "Standard Net 30 payment terms are reasonable and balanced",
    "Delaware governing law provides efficient dispute resolution",
  ],
  overall_risk_score: 68,
  negotiating_power: "Weak" as const,
};

export const DEMO_POWER = {
  contract_id: DEMO_CONTRACT_ID,
  power_score: 58,
  power_label: "Strongly Favors Counterparty",
  key_imbalances: [
    {
      clause: "Termination clause",
      why: "Company can terminate immediately without notice or severance, while you have no reciprocal protections. This creates extreme asymmetry in the employment relationship.",
      score: 22,
    },
    {
      clause: "Non-compete clause",
      why: "The non-compete is overly broad (50 miles, 2 years) and covers work outside the company's actual business, giving them control over your career decisions.",
      score: 18,
    },
    {
      clause: "IP Assignment clause",
      why: "Full assignment of all IP including personal projects created on your own time significantly exceeds what is necessary to protect the company's legitimate interests.",
      score: 18,
    },
  ],
  leverage_points: [
    "Request a non-compete scope reduction to match your actual role and industry",
    "Push for 30-day notice period before termination",
    "Negotiate IP assignment to only cover work created within the scope of your duties",
    "Add mutual indemnification with equal obligations for both parties",
    "Request severance pay equivalent to 30 days upon termination without cause",
  ],
};

export const DEMO_SCAN_JOB = {
  id: DEMO_JOB_ID,
  contract_id: DEMO_CONTRACT_ID,
  status: "complete" as const,
  progress_pct: 100,
  created_at: new Date().toISOString(),
  completed_at: new Date().toISOString(),
};